### ISSUE TITLE
Release RiboViz 2.0

### ISSUE THREAD

**Issue by mikej888** [riboviz/riboviz#182]
Release preparation tickets (labelled [R2.0](https://github.com/riboviz/RiboViz/labels/R2.0)):

* [all](https://github.com/riboviz/RiboViz/issues?utf8=%E2%9C%93&q=label%3AR2.0)
* [closed](https://github.com/riboviz/RiboViz/issues?q=label%3AR2.0+is%3Aclosed)
* [open](https://github.com/riboviz/RiboViz/labels/R2.0)

Pull requests to be merged into `develop` branch:

- [x] Generalise regression test vignette 155 #161 - pending @FlicAnderson review
- [x] Regression check install 160 #162 - pending above
- [x] Get current r 163 #164 - pending above
- [x] Merge nextflow-167 #180 - pending above

Issues to be completed:

- [x] Generalise riboviz.test.regression.test_vignette R2.0 #155 - see PR above
- [x] Port Python `riboviz.tools.prep_riboviz` workflow to Nextflow R2.0 #167 - see PR above
- [x] Allow user to configure `--output-stats` #186
- [x] Document recommended memory requirements #192
- [x] Document dependency versions #183
- [x] Review each item of documentation in `develop` #185
- [x] Explore running RiboViz on Eddie #59
- [x] Refactor generate_stats_figs.R R2.0 #32 
- [ ] Process mouse data for Premal and John R2.0 #96 (optional)
- [ ] Prepare Premal's yeast data for use with RiboViz  R2.0 #39 (optional)
- [ ] Break fork relationship between shahpr/RiboViz and riboviz/RiboViz R2.0 #135 (optional)

Release preparation [1d]

- [x] Add Bala, Siyin to Contributors in `docs/acks.md`.
- [x] Merge develop branch into master branch.
- [x] Rerun all tests inc. regression tests with Python + Nextflow.
- [x] Reserve DOI on Figshare and add a citation to Citing RiboViz in `README.md` (relates to Deposit RiboViz 2.0 and get a citable DOI R2.0 #173).
- [x] Update `README.md` Releases table.
- [x] Tag release in repository.
- [x] Build 2.0 DataSync and GitHub data resources.
- [x] Deposit RiboViz 2.0 to Figshare.

**Comment by mikej888** [comment]
Tiimescale to be discussed at meeting on 10/06/20.

**Comment by mikej888** [comment]
* Tag 2.0, https://github.com/riboviz/riboviz/tree/2.0
* Release 2.0, https://github.com/riboviz/riboviz/releases/tag/2.0
* Figshare deposit, https://figshare.com/articles/riboviz_software_for_analysis_and_visualization_of_ribosome_profiling_datasets/12624200
* DOI for above, https://doi.org/10.6084/m9.figshare.12624200
* Regression test data, https://github.com/riboviz/regression-test-data-2.0
