### ISSUE TITLE
Complete roxygen2-style documentation for CombineFrequencies()

### ISSUE THREAD

**Issue by FlicAnderson** [riboviz/riboviz#262]
Via #153 

Complete roxygen2-style documentation for `CombineFrequencies()` function in `read_count_functions.R`: 
 - [ ] Add information on what the function returns
 - [ ] Complete & check the example will run - this wasn't tested in #153 due to time constraints.
 - [ ] Add information on what possible tests for the function could be (e.g. for #259 testing implementation)
 - [ ] Potentially refactor this function as for loop isn't best method for this... (potentially separate issue as this issue is re: documentation?)

```
#' CombineFrequencies(): function to get position-specific frequencies across all genes
#' 
#' @param allfr matrix, multi-gene position-specific consensus matrix
#' 
#' @return TODO
#' 
#' @examples 
#' TODO: complete & test this example: may need to specify length_id?
#' gene_names <- rhdf5::h5ls(hd_file = "vignette/output/WTnone/WTnone.h5", recursive = 1)$name
#' fr0 <- mclapply(gene_names, function(gene) {PositionSpecificConsensusMatrix(gene = gene, pos_IR = out[[gene]], cframe = 0, length_id = length_id)}, mc.cores = num_processes)
#' allfr0 <- do.call(rbind, fr0)
#' CombineFrequencies(allfr0)
#' 
#' @export
CombineFrequencies <- function(allfr) {
  alph <- c("A", "C", "G", "T")
  nt_sp_freq <- c()
  for (i in alph) {
    nt_sp_freq <- rbind(nt_sp_freq, colSums(allfr[rownames(allfr) == i, ])) # Get position-specific counts/freq of a nt across all genes for reads of a particular length and frame
  }
  nt_sp_freq <- t(nt_sp_freq / colSums(nt_sp_freq)) # Convert total counts to freq OR freq to normalized frequencies
  colnames(nt_sp_freq) <- alph
  return(nt_sp_freq)
}
#TEST: CombineFrequencies(): TODO
```
