### ISSUE TITLE
Release riboviz 2.2

### ISSUE THREAD

**Issue by mikej888** [riboviz/riboviz#408]
Tickets labelled R2.2:

* [open](https://github.com/riboviz/RiboViz/labels/R2.2)
* [closed](https://github.com/riboviz/RiboViz/issues?q=label%3AR2.2+is%3Aclosed)
* [all](https://github.com/riboviz/RiboViz/issues?utf8=%E2%9C%93&q=label%3AR2.2)

Release preparation:
 
- [x] Double-check documentation related to #324.
- [x] See [docs/developer/releasing.md](https://github.com/riboviz/riboviz/blob/develop/docs/developer/releasing.md).
- [x] Update the README.md and citation to refer to riboviz 2 preprint.
- [x] Create new integration test dataset for 2.2 #344
- [x] Deposit riboviz 2.2 to Figshare.

**Comment by mikej888** [comment]
Tickets labelled R2.2:

* [open](https://github.com/riboviz/RiboViz/labels/R2.2)
* [closed](https://github.com/riboviz/RiboViz/issues?q=label%3AR2.2+is%3Aclosed)
* [all](https://github.com/riboviz/RiboViz/issues?utf8=%E2%9C%93&q=label%3AR2.2)

Release preparation:
 
- [ ] See [docs/developer/releasing.md](https://github.com/riboviz/riboviz/blob/develop/docs/developer/releasing.md).
- [ ] Create new integration test dataset for 2.2 #344
- [ ] Deposit RiboViz 2.2 to Figshare.

**Comment by mikej888** [comment]
* Tag 2.2: https://github.com/riboviz/riboviz/tree/2.2
* Release 2.2: https://github.com/riboviz/riboviz/releases/tag/2.2
* 2.2 test data: https://github.com/riboviz/test-data-2.2
* Figshare: https://figshare.com/articles/riboviz_software_for_analysis_and_visualization_of_ribosome_profiling_datasets/12624200
* DOI:  https://doi.org/10.6084/m9.figshare.12624200
