### ISSUE TITLE
Build release 2.0,beta

### ISSUE THREAD

**Issue by mikej888** [riboviz/riboviz#99]
Release preparation tickets (labelled [R2.0](https://github.com/riboviz/RiboViz/labels/R2.0)):

* [all](https://github.com/riboviz/RiboViz/issues?utf8=%E2%9C%93&q=label%3AR2.0)
* [closed](https://github.com/riboviz/RiboViz/issues?q=label%3AR2.0+is%3Aclosed)
* [open](https://github.com/riboviz/RiboViz/labels/R2.0)

Release preparation (completion of following tickets and merging of branches into "develop"):

- [x] Calculate read frame #89 - @ewallace 
- [x] Extend RiboViz to use UMI-tools for demultiplexing #84 - @mikej888
- [x] Clearer documentation for prep_riboviz.py call #80 - @mikej888
- [x] Rename config.yaml variables for consistency #86 - @mikej888
- [x] Remove sample prefix from file names #114 - @mikej888
- [x] Add git commit hash etc to log #90 - @mikej888
- [x] Update prep_riboviz.py to log versions of 3rd party tools invoked #123 - @mikej888
- [x] Insert provenance comments into tsv files #115 - @mikej888
- [x] Count the reads at each processing step for each sample #108  - @mikej888
- [x] Update regression tests to optionally validate against output files only #131 @mikej888
- [x] Do not multi-map rRNA/contaminant reads #127 @mikej888
- [x] Add helpful error if attempt to run RiboViz with Pytthon 2 #132 @mikej888 
- [x] Update prep_riboviz.py to infer rscripts directory from riboviz module location and to use argparse R2.0 #140 @mikej88
- [x] Issue in R Interactive Sessions Caused by get_Rscript_filename() returning NA #134 @FlicAnderson 
- [x] Investigate whether Shiny website directory can be purged from repository history #139 @mikej888
- [x] Confirm that version number is 2.0. - all (2.0.beta)
- [x] Confirm author and funder list for README.md #148
- [x] Provide a recommended citation #46
- [x] Add a copyright statement #45 @mikej888

Release:

- [x] Accelerate 2.0-beta release onto master branch for discoverability? #130
- [x] Merge develop into master branch - @mikej888
- [ ] Tag release in repository - @mikej888
- [x] Build 2.0.beta DataSync and GitHub data resources #137 @mike888

**Comment by mikej888** [comment]
Removed:

> - [ ] Create new Git repository with output files from run on vignette_config.yaml for use with test_vignette.py regression tests (these can replace use of DataSync)

as Git has a limit of 1GB on Git repositories (and free Git-LFS usage) and the RiboViz test files occupy ~1.5GB

**Comment by ewallace** [comment]
Question if containerization #107 is necessary before the release.

**Comment by mikej888** [comment]
> Suspect containerization #107 is necessary before the release.

Preparing a release is necessary before containerization to provide an stable version to initially go into a container. Any container would be a distinct artefact from the RiboViz software itself - a container is a useful and usable delivery and deployment vehicle.

A release also provides us with a means to close off some of the work that is in progress, before deciding upon the next steps.

Distributing the release prior to containerization allows users to use the new version if they wish  (some users may want to install RiboViz natively to avoid any additional container-incurred overhead) while not precluding distribution of a containerized version when that is available

**Comment by ewallace** [comment]
At software engineering meeting 12/2/20, we will decide on minimum requirements for progress on `generate-stats-figs.R` #32, before accelerating the release in beta #130.

**Comment by FlicAnderson** [comment]
See relevant issue #134 for issue breaking interactive R behaviours (get_Rscript_filename() at fault)

**Comment by mikej888** [comment]
Version tag will be 2.0.beta

**Comment by kavousan** [comment]
Plan for beta:

- @FlicAnderson completes #134 week beginning 17 Feb
- @mikej888 issues the beta #137 as soon as reasonably possible after that.
- We embark on testing the beta (which requires some more development work)
- @shahpr helps with #135 in parallel

**Comment by mikej888** [comment]
https://github.com/riboviz/riboviz/releases/tag/2.0.beta
